# Generated by Django 2.0.1 on 2018-03-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterCopy',
            fields=[
                ('chapterid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chapter_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChapterCopyCopy',
            fields=[
                ('chapterid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chapter_copy_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChapterCopyCopy1',
            fields=[
                ('chapterid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chapter_copy_copy1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NovelCopy',
            fields=[
                ('novelid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('sort', models.CharField(max_length=100)),
                ('novelname', models.CharField(max_length=100)),
                ('novelimg', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'novel_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NovelCopyCopy',
            fields=[
                ('novelid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('sort', models.CharField(max_length=100)),
                ('novelname', models.CharField(max_length=100)),
                ('novelimg', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'novel_copy_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Twokeys',
            fields=[
                ('chapterid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('novelid', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'twoKeys',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='bussiness',
            name='code',
            field=models.CharField(default='null', max_length=32, null=True),
        ),
    ]
