# Generated by Django 2.0.1 on 2018-03-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_host_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='id',
            field=models.IntegerField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
