# Generated by Django 2.0.1 on 2018-03-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_auto_20180305_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='b',
            new_name='bi',
        ),
    ]
